apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: onboarding-namespaceconfig
spec:
  annotationSelector:
    matchExpressions:
      - key: che.eclipse.org/username
        operator: Exists
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: standard-sandbox
          namespace: {{ .Name }}
        spec:
          hard:
            pods: "4"
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          creationTimestamp: null
          name: {{ .Name }}-pipeline-rb
          namespace: {{ .Name }}
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - kind: ServiceAccount
          name: pipeline
          namespace: admin-cicd
    - objectTemplate: |
        kind: DevWorkspace
        apiVersion: workspace.devfile.io/v1alpha2
        metadata:
          name: onboarding-workspace
          namespace: {{ .Name }}
        spec:
          routingClass: che
          started: true
          contributions:
            - name: ide
              uri: "https://raw.githubusercontent.com/wael2000/devspaces/main/pipelines/devfile.yaml"
          template:
            projects:
              - name: onboarding-docs
                git:
                  remotes:
                    origin: https://github.com/eclipse-che/che-docs
            components:
              - name: tooling-container
                container:
                  image: quay.io/devfile/universal-developer-image:ubi8-latest
