apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-nodejs-mongodb
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector1
  events:
    preStart:
      - init-container-command
  components:
    - name: checode
      volume: {}
    - name: che-code-injector1
      container:
        image: registry.redhat.io/devspaces/code-rhel8
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: nodejs-workspace
spec:
  started: true
  contributions:
    - kubernetes:
        name: che-code-nodejs-mongodb
      name: che-code-nodejs-mongodb
  routingClass: che
  template:
    attributes:
      controller.devfile.io/devworkspace-config:
        name: devworkspace-config
        namespace: openshift-operators
      controller.devfile.io/storage-type: per-workspace
    components:
      - name: nodejs
        container:
          image: registry.redhat.io/devspaces/udi-rhel8
          env:
            - name: SECRET
              value: 220fd770-c028-480d-8f95-f84353c7d55a
            - name: NODE_ENV
              value: production
          endpoints:
            - exposure: public
              name: nodejs
              targetPort: 8080
            - name: che-code
              attributes:
                type: main
                cookiesAuthEnabled: true
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
            - name: code-redirect-1
              attributes:
                discoverable: false
                urlRewriteSupported: false
                contributed-by: che-code.eclipse.org
              targetPort: 13131
              exposure: public
              protocol: http
            - name: code-redirect-2
              attributes:
                discoverable: false
                urlRewriteSupported: false
                contributed-by: che-code.eclipse.org
              targetPort: 13132
              exposure: public
              protocol: http
            - name: code-redirect-3
              attributes:
                discoverable: false
                urlRewriteSupported: false
                contributed-by: che-code.eclipse.org
              targetPort: 13133
              exposure: public
              protocol: http
          memoryLimit: 2.07G
          mountSources: true
          volumeMounts:
            - name: npm
              path: /home/user/.npm
            - name: checode
              path: /checode
          command:
            - /checode/entrypoint-volume.sh
          memoryRequest: 256Mi
          cpuLimit: 500m
          cpuRequest: 30m
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-endpoint/code-redirect-1: 13131
          che-code.eclipse.org/contribute-endpoint/code-redirect-2: 13132
          che-code.eclipse.org/contribute-endpoint/code-redirect-3: 13133
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 1G
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: nodejs
      - name: npm
        volume:
          size: 1G
      - name: mongo
        container:
          image: registry.redhat.io/rhscl/mongodb-36-rhel7
          env:
            - name: MONGODB_USER
              value: user
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_DATABASE
              value: guestbook
            - name: MONGODB_ADMIN_PASSWORD
              value: password
          endpoints:
            - name: mongodb
              exposure: internal
              targetPort: 27017
          memoryLimit: 512Mi
          mountSources: false
          volumeMounts:
            - name: mongo-storage
              path: /var/lib/mongodb/data
      - name: mongo-storage
        volume:
          size: 1G
    commands:
      - id: 1-run
        exec:
          label: Run the application
          component: nodejs
          workingDir: ${PROJECTS_ROOT}/nodejs-mongodb-sample
          commandLine: npm install && node --inspect=9229 app.js
          group:
            kind: run
    projects:
      - name: nodejs-project
        git:
          remotes:
            origin: https://github.com/devspaces-samples/nodejs-mongodb-sample
