apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: waas-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: waas-trigger-binding
      name: waas-trigger
      template:
        ref: waas-trigger-template
